name: Build and Push Container Image

on:
  workflow_dispatch:
    inputs:
      version_to_download:
        description: 'Version to download'
        required: true
      docker_tag:
        description: 'Docker image tag'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and prepare context
      run: |

        mvn -B clean package -DskipTests
        

        mkdir -p build/app
        cp target/*.jar build/app/app.jar
        

        echo "Build context contents:"
        ls -R build/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: build
        push: true
        tags: |
          ghcr.io/deja-vu101/mobile:${{ github.event.inputs.docker_tag }}
          ghcr.io/deja-vu101/mobile:latest
        file: Dockerfile
