name: Build and Push Container Image

on:
  workflow_dispatch:
    inputs:
      version_to_download:
        description: 'Version to download'
        required: true
      docker_tag:
        description: 'Docker tag'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read  # Змінено з write на read, оскільки ми тільки завантажуємо

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java with Auth
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Maven Settings
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Verify Package Exists
      run: |
        curl -sS -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -o /dev/null -w "%{http_code}" \
          https://maven.pkg.github.com/Deja-Vu101/mobile-app/com/mobile/mobile/${{ github.event.inputs.version_to_download }}/maven-metadata.xml | \
          grep -q 200 || (echo "Package not found" && exit 1)

    - name: Download Artifact
      id: download
      run: |
        mkdir -p build/app
        mvn dependency:get \
          -DgroupId=com.mobile \
          -DartifactId=mobile \
          -Dversion=${{ github.event.inputs.version_to_download }} \
          -Dpackaging=jar \
          -Dtransitive=false \
          -DremoteRepositories=github::default::https://maven.pkg.github.com/${{ github.repository }}
        
        cp $HOME/.m2/repository/com/mobile/mobile/${{ github.event.inputs.version_to_download }}/mobile-${{ github.event.inputs.version_to_download }}.jar build/app/app.jar
        echo "DOCKER_TAG=${{ github.event.inputs.docker_tag }}" >> $GITHUB_OUTPUT

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: build
        push: true
        tags: ghcr.io/deja-vu101/mobile:${{ steps.download.outputs.DOCKER_TAG }}
        file: build/Dockerfile
