name: Build and Push Container Image

on:
  workflow_dispatch:
    inputs:
      version_to_download:
        description: 'Version to use'
        required: true
      docker_tag:
        description: 'Docker tag'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Потрібно для push у container registry

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Prepare build context
      run: |
        # Build JAR
        mvn -B clean package -DskipTests
        
        # Prepare Docker context
        mkdir -p build/app
        cp target/*.jar build/app/app.jar
        
        # Verify structure
        echo "Build context contents:"
        ls -la build/app/
        [ -f build/app/app.jar ] || (echo "app.jar not found!" && exit 1)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: build
        push: true
        tags: ghcr.io/deja-vu101/mobile:${{ github.event.inputs.docker_tag }}
        file: build/Dockerfile
