name: Build and Push Container Image

on:
  workflow_dispatch:
    inputs:
      version_to_download:
        description: 'Version to use'
        required: true
      docker_tag:
        description: 'Docker tag'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build JAR and prepare context
      run: |
        # Збираємо JAR
        mvn -B clean package -DskipTests
        
        # Готуємо папку для Docker
        mkdir -p build/app
        cp target/*.jar build/app/app.jar
        
        # Перевіряємо структуру
        echo "Build context structure:"
        ls -la build/
        ls -la build/app/

    - name: Validate Dockerfile
      run: |
        echo "Dockerfile contents:"
        cat build/Dockerfile
        grep -q "COPY app/app.jar" build/Dockerfile || (echo "Missing COPY instruction" && exit 1)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: build
        push: true
        tags: |
          ghcr.io/deja-vu101/mobile:${{ github.event.inputs.docker_tag }}
          ghcr.io/deja-vu101/mobile:latest
        file: build/Dockerfile
