name: Build and Push Container Image

on:
  workflow_dispatch:
    inputs:
      version_to_download:
        description: 'Version of the artifact to download from GitHub Packages'
        required: true
      docker_tag:
        description: 'Tag to use for the Docker image'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Download and prepare artifact
      id: get-artifact
      run: |
        mvn dependency:get \
          -DgroupId=com.mobile \
          -DartifactId=mobile \
          -Dversion=${{ github.event.inputs.version_to_download }} \
          -DremoteRepositories=github::default::https://maven.pkg.github.com/${{ github.repository }}
        
        mkdir -p build/app
        cp $HOME/.m2/repository/com/mobile/mobile/${{ github.event.inputs.version_to_download }}/mobile-${{ github.event.inputs.version_to_download }}.jar build/app/app.jar
        
        echo "DOCKER_TAG=${{ github.event.inputs.docker_tag }}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: build/ 
        push: true
        tags: ghcr.io/deja-vu101/mobile:${{ steps.get-artifact.outputs.DOCKER_TAG }}
        file: build/Dockerfile  
