name: Build and Push Container Image

on:
  workflow_dispatch:
    inputs:
      version_to_download:
        description: 'Version to use'
        required: true
      docker_tag:
        description: 'Docker tag'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # 1. Checkout code
    - uses: actions/checkout@v3

    # 2. Set up Java
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Prepare build context (ВАШ КРОК)
    - name: Prepare build context
      run: |
        # Build JAR
        mvn -B clean package -DskipTests
        
        # Prepare Docker context
        mkdir -p build/app
        cp target/*.jar build/app/app.jar
        
        # Verify structure
        echo "Final structure before build:"
        ls -R build/

    # 4. Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 5. Login to GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 6. Build and push image (ВАШ КРОК)
    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/deja-vu101/mobile:${{ github.event.inputs.docker_tag }}
        file: build/Dockerfile
