name: Build and Push Container Image

on:
  workflow_dispatch:
    inputs:
      version_to_download:
        description: 'App version to download'
        required: true
      docker_tag:
        description: 'Docker tag to push'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download JAR artifact from GitHub Packages
        run: |
          mkdir -p app
          curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            -L https://maven.pkg.github.com/Deja-Vu101/mobile-app/com/mobile/mobile/${{ github.event.inputs.version_to_download }}/mobile-${{ github.event.inputs.version_to_download }}.jar \
            -o app/app.jar

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mobile:${{ github.event.inputs.docker_tag }}
          file: Dockerfile
