name: Publish to GitHub Packages

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn -B clean package
      
    - name: Run Tests
      run: mvn test
      
    - name: Publish to GitHub Packages
      uses: actions/upload-artifact@v3
      with:
        name: mobile-operator-package
        path: target/*.jar
        
    - name: Publish to GitHub Packages Registry
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Generate Changelog
      if: github.event_name == 'release'
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        toTag: ${{ github.event.release.tag_name }}
        configuration: ".github/changelog-config.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}