name: Publish to GitHub Packages

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn -B clean package
      
    - name: Run Tests
      run: mvn test
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mobile-operator-package
        path: target/*.jar
        
    - name: Publish to GitHub Packages Registry
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger Container Build Workflow
      if: success()  # Only run if all previous steps succeeded
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: build-and-push-container-image.yml
        token: ${{ secrets.GITHUB_TOKEN }}
        inputs: '{ "version_to_download": "${{ steps.publish.outputs.version_to_download }}", "docker_tag": "${{ steps.publish.outputs.docker_tag }}" }'
        ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
