name: Publish to GitHub Packages

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
    
    # Основна збірка з пропуском тестів
    - name: Build and Test
      run: |
        mvn -B clean package -DskipTests
        
    # Додаткова перевірка (без інтеграційних тестів)
    - name: Run Unit Tests Only
      run: mvn -B test -Dtest=!CallServiceIntegrationTest
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mobile-operator-package
        path: target/*.jar
        
    - name: Publish to GitHub Packages
      run: mvn -B deploy -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version
      id: extract_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version_to_download=$VERSION" >> $GITHUB_OUTPUT
        echo "docker_tag=${VERSION%-SNAPSHOT}" >> $GITHUB_OUTPUT  # Прибирає -SNAPSHOT для docker тегів

    - name: Trigger Container Build
      if: success()
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: build-and-push-container-image.yml
        token: ${{ secrets.GITHUB_TOKEN }}
        inputs: |
          {
            "version_to_download": "${{ steps.extract_version.outputs.version_to_download }}",
            "docker_tag": "${{ steps.extract_version.outputs.docker_tag }}"
          }
        ref: ${{ github.ref_name }}
